version: '2'
services:
  db:
    image: postgres:9.5.6-alpine
    container_name: db

  app:
    build: .
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
